# Pipeline schedule vars
# KI_BUILD_TYPE
#   daily
#   monthly
#   release

variables:
  CONTAINER_NAME: kicad
  GL_CONTAINER_ROOT: ${CI_REGISTRY}/${CI_PROJECT_PATH}

stages:
  - build
  - deploy

.template:build_base:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: build
  variables:
    GL_CONTAINER: "${GL_CONTAINER_ROOT}/${CONTAINER_NAME}"
  before_script:
    - apk add --no-cache bash
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  artifacts:
    paths:
      - docker_tags.txt
    
.template:build:
  extends: .template:build_base
  script:
    - docker build --pull -t kicad:build-temp -f ${DOCKERFILE_PATH} .
    - echo $KI_BUILD_TYPE
    - echo $CONTAINER_TAG
    - echo $GL_CONTAINER
    - /bin/bash ./tag-helper.sh -c kicad:build-temp -t $KI_BUILD_TYPE -b $CONTAINER_TAG -i $GL_CONTAINER -p
    
.template:build_release:
  extends: .template:build_base
  script:
    - docker build --pull -t kicad:build-temp -f ${DOCKERFILE_PATH} --build-arg="KICAD_VERSION=${VERSION}" .
    - echo $KI_BUILD_TYPE
    - echo $CONTAINER_TAG
    - echo $GL_CONTAINER
    - /bin/bash ./tag-helper.sh -c kicad:build-temp -t $KI_BUILD_TYPE -b $CONTAINER_TAG -r $VERSION -i $GL_CONTAINER -p

.template:deploy_to_dh:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: deploy
  before_script:
    - apk add --no-cache bash
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DH_PASSWORD" | docker login -u "$DH_USER" docker.io --password-stdin
    - echo "$GH_TOKEN" | docker login -u "$GH_USER" ghcr.io --password-stdin
  script:
    - /bin/bash ./deploy-helper.sh -i index.docker.io/kicad/kicad
    - /bin/bash ./deploy-helper.sh -i ghcr.io/kicad/kicad

build_nightly:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "daily"

deploy_nightly:
  extends: .template:deploy_to_dh
  dependencies:
    - build_nightly
  variables:
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "daily"
  
build_nightly_monthly:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "monthly"

deploy_nightly_monthly:
  extends: .template:deploy_to_dh
  dependencies:
    - build_nightly_monthly
  variables:
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "monthly"

build_8:
  extends: .template:build_release
  variables:
    DOCKERFILE_PATH: Dockerfile.8.0-stable
    CONTAINER_TAG: "8.0"
  rules:
    - if: $KI_BUILD_TYPE == "release"

deploy_8:
  extends: .template:deploy_to_dh
  rules:
    - if: $KI_BUILD_TYPE == "release"
  dependencies:
    - build_8
  variables:
    CONTAINER_TAG: "8.0"