variables:
  CONTAINER_NAME: kicad
  GL_CONTAINER_ROOT: ${CI_REGISTRY}/${CI_PROJECT_PATH}

stages:
  - build
  - deploy

.template:build:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: build
  variables:
    CONTAINER_IMAGE: ${CONTAINER_NAME}:${CONTAINER_TAG}
    GL_CONTAINER: ${GL_CONTAINER_ROOT}/${CONTAINER_IMAGE}
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build --pull -t ${CONTAINER_IMAGE} -f ${DOCKERFILE_PATH} .
    - docker tag ${CONTAINER_IMAGE} ${GL_CONTAINER}
    - docker push ${GL_CONTAINER}
    - echo "${CONTAINER_IMAGE}" >> built_image.txt
    - echo "${GL_CONTAINER}" >> built_gl_path.txt
  artifacts:
    paths:
      - built_image.txt
      - built_gl_path.txt

.template:deploy_to_dh:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: deploy
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker login -u ${DH_USER} -p ${DH_PASSWORD} docker.io
  script:
    - CONTAINER_IMAGE=$(cat built_image.txt); echo $CONTAINER_IMAGE
    - GL_CONTAINER=$(cat built_gl_path.txt); echo $GL_CONTAINER
    - DH_CONTAINER=index.docker.io/kicad/$CONTAINER_IMAGE; echo $DH_CONTAINER
    - docker pull $GL_CONTAINER
    - docker tag $GL_CONTAINER $DH_CONTAINER
    - docker push $DH_CONTAINER


build_nightly:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
  only:
    - triggers
    - web
    - schedules
    
deploy_nightly:
  extends: .template:deploy_to_dh
  dependencies:
    - build_nightly
  variables:
    CONTAINER_TAG: nightly
  only:
    - triggers
    - web
    - schedules