variables:
  CONTAINER_IMAGE: kicad
  GL_CONTAINER_ROOT: ${CI_REGISTRY}/${CI_PROJECT_PATH}

stages:
  - build
  - deploy

.template:build:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: build
  variables:
    CONTAINER_NAME: ${CONTAINER_IMAGE}:${CONTAINER_TAG}
    GL_CONTAINER: ${GL_CONTAINER_ROOT}/${CONTAINER_NAME}
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build --pull -t ${CONTAINER_NAME} -f ${DOCKERFILE_PATH} .
    - docker tag ${CONTAINER_NAME} ${GL_CONTAINER}
    - docker push ${GL_CONTAINER}

.template:deploy_to_dh:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: deploy
  variables:
    CONTAINER_NAME: ${CONTAINER_IMAGE}:${CONTAINER_TAG}
    GL_CONTAINER: ${GL_CONTAINER_ROOT}/${CONTAINER_NAME}
    DH_CONTAINER: index.docker.io/kicad/${CONTAINER_NAME}
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker login -u ${DH_USER} -p ${DH_PASSWORD} docker.io
  script:
    - docker pull ${GL_CONTAINER}
    - docker tag ${GL_CONTAINER} ${DH_CONTAINER}
    - docker push ${DH_CONTAINER}


build nightly:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
  only:
    - triggers
    - web
    
deploy nightly:
  extends: .template:deploy_to_dh
  variables:
    CONTAINER_TAG: nightly
  only:
    - triggers
    - web