# Pipeline schedule vars
# KI_BUILD_TYPE
#   daily
#   monthly
#   release

variables:
  CONTAINER_NAME: kicad
  GL_CONTAINER_ROOT: ${CI_REGISTRY}/${CI_PROJECT_PATH}

stages:
  - build
  - deploy

.template:build:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: build
  variables:
    GL_CONTAINER: "${GL_CONTAINER_ROOT}/${CONTAINER_NAME}"
  before_script:
    - apk add --no-cache bash
    - unlink /bin/sh
    - ln -s /bin/bash /bin/sh
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build --pull -t kicad:build-temp -f ${DOCKERFILE_PATH} .
    - echo $KI_BUILD_TYPE
    - echo $CONTAINER_TAG
    - echo $GL_CONTAINER
    - /bin/bash ./tag-helper.sh -c kicad:build-temp -t $KI_BUILD_TYPE -b $CONTAINER_TAG -r -i $GL_CONTAINER
  artifacts:
    paths:
      - docker_tags.txt

.template:deploy_to_dh:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: deploy
  before_script:
    - apk add --no-cache bash
    - unlink /bin/sh
    - ln -s /bin/bash /bin/sh
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker login -u ${DH_USER} -p ${DH_PASSWORD} docker.io
  script:
    - /bin/bash ./deploy-helper.sh -i index.docker.io/kicad/kicad

build_nightly:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "daily"

build_nightly_monthly:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "monthly"

build_7:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.7.0-stable
    CONTAINER_TAG: "7.0"
  rules:
    - if: $KI_BUILD_TYPE == "release"

deploy_nightly:
  extends: .template:deploy_to_dh
  dependencies:
    - build_nightly
  variables:
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "daily"
    - if: $KI_BUILD_TYPE == "monthly"

deploy_7:
  extends: .template:deploy_to_dh
  rules:
    - if: $KI_BUILD_TYPE == "release"
  dependencies:
    - build_7
  variables:
    CONTAINER_TAG: "7.0"