.template:build:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: build
  variables:
    CONTAINER_NAME: ${CONTAINER_IMAGE}:${CONTAINER_TAG}
    GL_CONTAINER: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CONTAINER_NAME}
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build --pull -t ${CONTAINER_NAME} -f ${DOCKERFILE_PATH} .
    - docker tag ${CONTAINER_NAME} ${GL_CONTAINER}
    - docker push ${GL_CONTAINER}

build nightly:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_IMAGE: kicad
    CONTAINER_TAG: nightly
  only:
    - triggers
    - web